### ISSUE TITLE
heroku_app in private space won't lock

### ISSUE THREAD

**Issue by talbright** [terraform-providers/terraform-provider-heroku#118]
```sh
terraform -v
Terraform v0.11.8
+ provider.heroku v1.3.0
```

### Affected Resource(s)
- heroku_space

### Terraform Configuration Files
```hcl
resource "heroku_app" "external_cc_app" {
  name   = "foo-app"
  region = "${var.region}"
  stack  = "heroku-16"
  space  = "foo-space"

  organization {
    name   = "${var.organization}"
    locked = true
  }

}
```

### Expected Behavior
`heroku_app` should be locked.

### Actual Behavior
`heroku_app` is not locked.

**Comment by crisp2u** [comment]
Hello, I'm also hitting this ? Are there any updates

**Comment by davidji99** [comment]
I can take a look at this in the next day or so.
