### ISSUE TITLE
Removing an app from Heroku breaks existing resources tied to that app

### ISSUE THREAD

**Issue by patrobinson** [terraform-providers/terraform-provider-heroku#126]
### Terraform Version
```
Terraform v0.11.8
+ provider.heroku v1.4.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- heroku_drain
- Any other resource that applies to an app

### Terraform Configuration Files
```hcl

resource "heroku_drain" "drain" {
    app = "${var.heroku_app}"
    url = "${var.url}"
}

```

### Expected Behavior
Terraform should remove the drain from the state file

### Actual Behavior
```
Error: Error refreshing state: 2 error(s) occurred:

* app_name.heroku_drain.drain: heroku_drain.drain: Error retrieving drain: Get https://api.heroku.com/apps/app_name/log-drains/drain-uuid: Couldn't find that app.
```

### Steps to Reproduce
1. Create an application manually
2. Create a drain with Terraform and point it to the application
3. Delete the application manually
4. Remove the drain from HCL

**Comment by patrobinson** [comment]
@davidji99 sure, that is a better way. But the provider I feel should handle this gracefully. If the application doesn't exist than the drain doesn't exist, so no sense trying to refresh the state or delete it, just remove it from the state

**Comment by talbright** [comment]
Thanks for letting us know about this issue! From my experience and understanding of Terraform, trying to manage resources both within HCL and outside of that manually is *always* going to be problematic regardless of the provider, and just the nature of working with Terraform. @davidji99 suggestion would be mine as well.

**Comment by patrobinson** [comment]
@talbright it doesn't _have_ to be problematic in this case though, you could implement a more graceful way of handling it. I would be happy to PR this, but I'm only going to invest the effort if the PR will be accepted.
