### ISSUE TITLE
Error Retrieving Heroku Addon -- Invalid Credentials Provided

### ISSUE THREAD

**Issue by armordog** [terraform-providers/terraform-provider-heroku#14]
### Description
I have a Heroku app provisioned via Terraform. That part works great.
The Heroku instance has a Papertrail add-on.
Importing the add on works fine. I see the correct id and attributes in the `.tfstate`.

After importing, running `terraform plan` or `terraform refresh` gives the error:
```
Error refreshing state: 1 error(s) occurred:

* heroku_addon.papertrail: heroku_addon.papertrail: Error retrieving addon: Get https://api.heroku.com/addons/papertrail-transparent-47380: Invalid credentials provided.
```

### Terraform Version
v0.10.2

### Affected Resource(s)
- heroku_addon

### Terraform Configuration Files
```hcl
provider "heroku" {
  email   = "${var.heroku_email}"
  api_key = "${var.heroku_api_key}"
}

# Create a new Heroku app
resource "heroku_app" "social_proxy" {
  name    = "${var.hk_app_name}"
  region  = "us"
  stack   = "cedar-14"

  config_vars {
    ---- snip ----
  }
}

resource "heroku_addon" "papertrail" {
  count = "${var.provision_papertrail_addon}" # boolean to add papertrail or not
  app  = "${heroku_app.social_proxy.name}"
  plan = "papertrail:choklad"
}
```

### Expected Behavior
Heroku add-on state should be retrieved from `https://api.heroku.com/addons/papertrail-transparent-47380` using same API key used when importing and when managing the Heroku app itself.

### Actual Behavior
Terraform gets an error response from `https://api.heroku.com/addons/papertrail-transparent-47380` indicating that invalid credentials were provided.

### Steps to Reproduce
`terraform plan`

### Important Factoids
1. Using cURL, I'm able to retrieve the add-on state by sending the API key in an `Authorization` header.
2. If I send no Authorization header, I get an error saying "There were no credentials in your `Authorization`  header.". This implies that Terraform is sending _something_ for authorization but it's incorrect.

**Comment by davidji99** [comment]
Hi,

Are you still using the provider? If so, does this issue still happen for you? Thanks!

**Comment by davidji99** [comment]
Closing this issue. Feel free to re-open or create a new one if needed.
