### ISSUE TITLE
resource "heroku_space" doesn't support providing custom VPC CIDRs.

### ISSUE THREAD

**Issue by DevBOFH** [terraform-providers/terraform-provider-heroku#168]
### Terraform Version
```
Terraform v0.11.11
```

### Heroku Provider Version
Run `terraform -v` to show core and any provider versions. A sample output could be:

```
Terraform v0.11.11
+ provider.heroku v1.7.3
```

### Affected Resource(s)
Please list the resources as a list, for example:
- heroku_space

### Details
Heroku supports providing a custom CIDR range upon creating a new private space. However, Terraform doesn't provide the same functionality.

Heroku Documentation can be found at: https://devcenter.heroku.com/articles/private-spaces#choosing-private-network-cidr-range

**Comment by talbright** [comment]
See #167

**Comment by DevBOFH** [comment]
Closing as #167 will implement this.
