### ISSUE TITLE
Clarify that "organization" means "team"

### ISSUE THREAD

**Issue by mars** [terraform-providers/terraform-provider-heroku#186]
"organization" is the old Heroku name for what is now Heroku Teams. That renaming did not penetrate into actually renaming the Platform API properties and hence this TF provider is still using "organization".

Revise the Provider docs to make this clear, or consider actually aliasing a new "team" attribute to the old "organization" to support more intuitive Terraform configuration.

**Comment by monkey-jeff** [comment]
#185 Should address this
