### ISSUE TITLE
Upgrade to v2 requires recreation of add-ons

### ISSUE THREAD

**Issue by billmoritz** [terraform-providers/terraform-provider-heroku#214]
### Terraform Version
```
Terraform v0.11.7
```

### Heroku Provider Version
Issue applies to the following upgrade paths
`provider.heroku v1.9.0` -> `provider.heroku v2.0.0`
`provider.heroku v1.9.0` -> `provider.heroku v2.0.1`

### Affected Resource(s)
- heroku_addon

### Terraform Configuration Files
```hcl
resource "heroku_addon" "redis" {
  app  = "foo"
  plan = "heroku-redis:private-7"

  config = {
    maxmemory_policy = "volatile-ttl"
  }
}
```
### Plan Output
```
-/+ heroku_addon.redis (new resource required)
      id:                                                         "6715ad3e-2efd-4f19-a3fc-9b0aeaabc123" => <computed> (forces new resource)
      app:                                                        "foo" => "foo"
      config.%:                                                   "2" => "1" (forces new resource)
      config.0.%:                                                 "1" => "" (forces new resource)
      config.0.maxmemory_policy:                                  "volatile-ttl" => "" (forces new resource)
      config.maxmemory_policy:                                    "" => "volatile-ttl" (forces new resource)
      config_vars.#:                                              "4" => <computed>
      name:                                                       "redis-sinuous-12312" => <computed>
      plan:                                                       "heroku-redis:private-7" => "heroku-redis:private-7"
      provider_id:                                                "resource12312312@heroku.com" => <computed>
```

### Debug Output
Available upon request. 

### Expected Behavior
Nothing changes. 

### Actual Behavior
The resource is replaced.

### Steps to Reproduce
1. Specify provider v1.9.0
2. `terraform apply`
3. Specify provider v2.0.0 or v2.0.1
4. `terraform apply`

### Important Factoids
I tried to rm and import the state but it still wants to recreate the resource with the following output:
```
-/+ heroku_addon.redis (new resource required)
      id:                                                         "6715ad3e-2efd-4f19-a3fc-9b0aeaabc123" => <computed> (forces new resource)
      app:                                                        "foo" => "foo"
      config.%:                                                   "" => "1" (forces new resource)
      config.maxmemory_policy:                                    "" => "volatile-ttl" (forces new resource)
      config_vars.#:                                              "4" => <computed>
      name:                                                       "redis-sinuous-12312" => <computed>
      plan:                                                       "heroku-redis:private-7" => "heroku-redis:private-7"
      provider_id:                                                "resource12312312@heroku.com" => <computed>
```

### References
- I believe this is related to #102

**Comment by davidji99** [comment]
Unless I'm mistaken here, #102 refers to having a better way of storing & referencing the value of an addon's config vars. For example in this [sample API response](https://devcenter.heroku.com/articles/platform-api-reference#add-on-info-response-example), #102 wanted to see `heroku_addon.config_vars` be a map of key/value pairs in state:
```
  "config_vars": {
    "FOO": "foo's value",
    "BAZ": "baz's value"
  },
```

The `heroku_addon` code does not explicitly set the `config` attribute so I wonder if that could be a problem.

Two solutions I can think of:
- Remove the `ForceNew` designation for the `config` attribute (quickest but not a great idea)
- Explore the use of `StateUpgraders` as `MigrateState` is deprecated. Will need to consult a bit further with Hashicorp on this.
