### ISSUE TITLE
Error: strconv.Atoi: parsing "": invalid syntax

### ISSUE THREAD

**Issue by James-Quigley** [terraform-providers/terraform-provider-heroku#223]
### Terraform Version
Terraform v0.12.5

### Heroku Provider Version
Run `terraform -v` to show core and any provider versions. A sample output could be:

```
Terraform v0.12.5
+ provider.heroku v2.1.0
```

### Affected Resource(s)
???

### Terraform Configuration Files
```hcl
resource "heroku_app" "greenroom" {
  name   = "tracer-greenroom"
  region = "virginia"
  space  = "tracer-production"

  organization {
    name = "tracer-ops"
  }

  stack = "heroku-18"
}

resource "heroku_addon" "greenroom_graphite" {
  app  = "${heroku_app.greenroom.name}"
  plan = "hostedgraphite:small"
}
```

### Debug Output
https://gist.github.com/James-Quigley/40e33125f05fb3d57474b63d3109e14e

### Expected Behavior
Successfully ran `plan` or at least said what was invalid

### Actual Behavior
``Error: strconv.Atoi: parsing "": invalid syntax`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -input=false`

### Important Factoids
Pretty sure this has to do with the 2.1.0 release. Downgrading to 2.0.3 is fine

**Comment by davidji99** [comment]
Thanks for reporting this @James-Quigley. I'll take a look.

**Comment by davidji99** [comment]
Hi @James-Quigley,

Were you already on terraform `v0.12.X` when you executed a `plan` with the provider version `v2.1.0`?

**Comment by James-Quigley** [comment]
@davidji99 The state had previously been created with Terraform v0.11.x and provider version < 2. I upgraded both to latest, and then encountered this issue.

**Comment by davidji99** [comment]
Thanks for the information. I think I'll have a fix shortly.
