### ISSUE TITLE
404's Break Refresh

### ISSUE THREAD

**Issue by Jefferson-Faseler** [terraform-providers/terraform-provider-heroku#237]
### Versions

```
Terraform v0.12.7
+ provider.heroku v2.1.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- addon_attachment
- maybe more?

Heroku gives developers the ability to replace addons in apps by essentially unplugging one addon and putting in another. For instance, what is considered the database of an app. This causes daily drift which `terraform refresh` is expected to handle. However when the old attachment is no longer there a 404 is returned.

### Expected Behavior
Using `terraform refresh` succeeds if the addon attachment is missing. Updating the state to report the deleted instance.

### Actual Behavior
When running `terraform refresh` it fails with:
```
Error: Error retrieving addon attachment: Get https://api.heroku.com/addon-attachments/<attachment-id>: Couldn't find that attachment.
```

**Comment by mars** [comment]
Hi Jefferson,

> This causes daily drift which terraform refresh is expected to handle.

**Terraform does not handle config drift.**  Some things, like changing computed values can be refreshed dynamically, but when resources Terraform created go missing, that is not automatically correctable.

Any operations that would change the Terraform configuration must be performed through Terraform, or else may require manipulation of the state to remove/replace the changed resources.

In a [Hashicorp blog article](https://www.hashicorp.com/blog/detecting-and-managing-drift-with-terraform), they offer some specific lifecycle configuration options that might help manage your situation.

The challenge of config drift is also documented in Heroku’s [Best Practices with Terraform](https://devcenter.heroku.com/articles/using-terraform-with-heroku#best-practices) section of the Dev Center.

I’d suggest making any changes to your configuration through Terraform to avoid this kind of breaking drift.
