### ISSUE TITLE
heroku_app config_vars go missing after upgrade to v2

### ISSUE THREAD

**Issue by tommymetz** [terraform-providers/terraform-provider-heroku#243]
When using provider.heroku v1.9.0, everything works fine and my config_vars are already present on the app. But when I upgrade to v2 it thinks that my config vars are gone and wants to create them again. I have this problem also when I upgrade terraform to v.0.12. Any idea why this would happen?

### Terraform Version
v0.11.14

### Heroku Provider Version
+ provider.heroku v2.2.1

### Affected Resource(s)
heroku_app config_vars

### Terraform Configuration Files

```
resource "heroku_app" "dev-frontend" {
  name = "${var.app}-dev-frontend"
  region = "us"

  organization {
    name = "dev-frontend"
    personal = false
  }

  depends_on = ["heroku_app.dev"]

  config_vars = {
    NODE_ENV = "production"
    NPM_CONFIG_PRODUCTION = "false"
    API_HOST = "https://${heroku_app.dev.heroku_hostname}"
    DOMAIN = testing.com"
    PRIMARY_COLOR = "#860037"
    SECONDARY_COLOR = "#7C6A55"
    ACCENT_COLOR = "#EFE9E5"
    GRADIENT_START = "#968877"
    GRADIENT_STOP = "#7C6A55"
    PRIMARY_BUTTON_FONT_COLOR = "#FFFFFF"
    TITLE = "Dev Frontend"
    EMAIL_ADDR_PLACEHOLDER = "student@testing.com"
    SSO_ENABLED = 0
    SSO_LINK=""
    SSO_NAME=""
  }
}
```

### Expected Behavior
It should already know the config_vars are present.

### Actual Behavior
It thinks it needs to recreate all the config_vars when I run `terraform plan`

```
  ~ heroku_app.dev-frontend
      config_vars.%:                                    "0" => "15"
      config_vars.EMAIL_ADDR_PLACEHOLDER:               "" => "student@testing.com"
      config_vars.NODE_ENV:                             "" => "production"
      config_vars.NPM_CONFIG_PRODUCTION:                "" => "false"
      config_vars.SSO_ENABLED:                          "" => "0"
      config_vars.SSO_LINK:                             "" => <computed>
      config_vars.SSO_NAME:                             "" => <computed>
      config_vars.YOU_API_HOST:                         "" => "https://dev-frontend.herokuapp.com"
      config_vars.ACCENT_COLOR:              "" => "#EFE9E5"
      config_vars.DOMAIN:                    "" => "testing.com"
      config_vars.GRADIENT_START:            "" => "#968877"
      config_vars.GRADIENT_STOP:             "" => "#7C6A55"
      config_vars.PRIMARY_BUTTON_FONT_COLOR: "" => "#FFFFFF"
      config_vars.PRIMARY_COLOR:             "" => "#860037"
      config_vars.SECONDARY_COLOR:           "" => "#7C6A55"
      config_vars.TITLE:                     "" => "Dev Frontend"
```

### Steps to Reproduce
When running version 1.9.0 it works fine and says "nothing to apply". Once I upgrade to v2 it thinks the config_vars aren't present.

**Comment by mars** [comment]
The internals of Terraform changed a lot with version 0.12, specifically you're seeing effect of how the Map type changed. The first apply on the new version re-populates its state.

That shouldn't change anything from the previous configuration applied to the Heroku app, but it always good to verify the upgrade in a less-risk environment, not production.

**Comment by tommymetz** [comment]
@mars thanks ok. We have a like 40 apps so it's a little stressful applying the update to all of them. But I'll see about testing it on an isolated instance first. Thanks for responding!

**Comment by davidji99** [comment]
@tommymetz, it should be a `noop`. It's what I experienced when vetting out the PR to support 0.12 in this provider: https://github.com/terraform-providers/terraform-provider-heroku/pull/179#issuecomment-497182245

**Comment by tommymetz** [comment]
@davidji99 thanks I appreciate it.
