### ISSUE TITLE
Support heroku pipeline config_vars

### ISSUE THREAD

**Issue by masutaka** [terraform-providers/terraform-provider-heroku#244]
This is a feature request.

I want you to support Heroku pipeline config_vars for using New Review Apps.

It seems Heroku Platform API supports pipeline config_vars. However, the API response mentions only the `test` stage.

```
$ curl -sn https://api.heroku.com/pipelines/{pipeline_id}/stage/production/config-vars \
> -H "Accept: application/vnd.heroku+json; version=3" | jq
{
  "id": "not_found",
  "message": "Pipeline config vars are only supported for the 'test' stage."
}

$ curl -sn https://api.heroku.com/pipelines/{pipeline_id}/stage/test/config-vars \
> -H "Accept: application/vnd.heroku+json; version=3" | jq
{}

$ curl -sn https://api.heroku.com/pipelines/{pipeline_id}/stage/review/config-vars \
> -H "Accept: application/vnd.heroku+json; version=3" | jq
{
  "FOO": "bar",
  "BAZ": "qux"
}
```

In addition, the documentation does not describe `{pipeline_coupling_stage}`.
https://devcenter.heroku.com/articles/platform-api-reference#pipeline-config-vars

### Terraform Version

v0.12.18

### Heroku Provider Version

v2.2.1

### Affected Resource(s)

- heroku_pipeline

**Comment by davidji99** [comment]
On initial review on this issue, it seems this is more of a feature request to Heroku to support pipeline config vars beyond just in the 'Test' stage. If so, I would suggest you contact Heroku support indicating your desire to have Heroku expand the current functionality. Therefore, if the Platform APIs do not provide the functionality in question, the provider cannot implement said functionality in the `heroku_pipeline` resource.

**Comment by masutaka** [comment]
As mentioned above, it seems the API also supports `review` stage.

```
$ curl -sn https://api.heroku.com/pipelines/{pipeline_id}/stage/review/config-vars \
> -H "Accept: application/vnd.heroku+json; version=3" | jq
{
  "FOO": "bar",
  "BAZ": "qux"
}
```

However, it's not written in the documentation, and the error response doesn't tell me that.

So, I created a ticket.
https://help.heroku.com/sharing/be328c00-a417-4b80-8020-99e151abfcad

**Comment by masutaka** [comment]
:link: https://help.heroku.com/810434

> The Pipeline Config Vars API only relates to the config vars that can be set at the pipeline level. These are:
>
> * Heroku CI config vars (`test` stage)
> * Review Apps config vars (`review` stage)
>
> The other stages, (`development`, `staging` & `production`) do not have stage-level config vars, only those on the apps within each stage.

As they say, the Pipeline Config Vars API also supports `review` stage.

So, could you support heroku pipeline config_vars?

**Comment by davidji99** [comment]
Oh I see. You're asking for a new resource essentially, `heroku_pipeline_config_var`.

**Comment by Jefferson-Faseler** [comment]
Is there any update on this? Has anyone claimed this issue?

**Comment by davidji99** [comment]
I started this today but realized that `heroku-go` needs to be updated to support the `GET` and `PATCH` request for pipeline config vars. I'll need to do that first.
