### ISSUE TITLE
Imported heroku_app should include buildpacks

### ISSUE THREAD

**Issue by mmrobins** [terraform-providers/terraform-provider-heroku#249]
After importing an existing heroku app

```
terraform import module.myappname.heroku_app.app myappname
```

The initial plans show that I'm adding buildpacks, even though the existing app has buildpacks

```
$ terraform plan
...
  # module.myappname.heroku_app.app will be updated in-place
  ~ resource "heroku_app" "app" {
      ..
      + buildpacks            = [
          + "heroku/ruby",
          + "https://github.com/heroku/heroku-buildpack-pgbouncer",
        ]
$ heroku buildpacks -a myappname
=== myappname Buildpack URLs
1. heroku/ruby
2. https://github.com/heroku/heroku-buildpack-pgbouncer
 ```

### Terraform and Heroku Provider Version

```
% terraform -v
Terraform v0.12.20
+ provider.heroku v2.1.2
```

### Affected Resource(s)

heroku_app

### Terraform Configuration Files
```hcl
resource "heroku_app" "app" {
  name   = var.app_name
  ...
  buildpacks = [
    "heroku/ruby",
    "https://github.com/heroku/heroku-buildpack-pgbouncer",
  ]
}

```

### Expected Behavior
After the initial `terraform import` the first `terraform plan` and `apply` should show the existing buildpacks.

### Actual Behavior
The initial `plan` shows that I'm adding buildpacks that are already there.

### References

This is similar to how `config_vars` don't show a diff until after the first `apply` https://github.com/terraform-providers/terraform-provider-heroku/issues/247

**Comment by thomsonyeh-czi** [comment]
+1 - I'm seeing the same issue on imported `heroku_app` resources in Terraform 0.12.24.
