### ISSUE TITLE
There should be a data source for `heroku_pipeline`

### ISSUE THREAD

**Issue by mmrobins** [terraform-providers/terraform-provider-heroku#267]
There should be a data source for `heroku_pipeline`.  If I want to separate heroku apps that share a pipeline into separate directories, they each end up managing the pipeline as a resource https://www.terraform.io/docs/providers/heroku/r/pipeline.html instead of just being able to reference and existing pipeline as a data source.

### Terraform and Heroku Provider Version

```
% terraform -v
Terraform v0.12.25
+ provider.heroku v2.4.1
+ provider.sumologic v2.0.1
```

### Expected Behavior

I would like to be able to reference an existing pipeline as data

```
data "heroku_pipeline" "mypipeline" {
  name = "mypipeline"
}

resource "heroku_app" "myapp" {
  pipeline = data.heroku_pipeline.mypipeline.id
}
```

**Comment by davidji99** [comment]
This should be pretty quick. I'll whip a PR.

**Comment by davidji99** [comment]
Circling back to this request, I found out that the Heroku Platform API does not allow a pipeline to be retrieved using its name if the pipeline has no apps associated to it. This makes it a bit more difficult to achieve what you're looking for @mmrobins unless `mypipeline` in your example already has an app associated to it.

**Comment by mmrobins** [comment]
Yeah, I've hit that weird case with an empty pipeline before too.  Also, only the user who created the empty pipeline can access it at all until an app gets put in the pipeline, and if you leave the pipeline empty for too long (hours?  days?) it gets deleted automatically.  Fortunately, most of the time I'm just adding an app to an existing pipeline that already has apps in it.  Thanks again for implementing this

**Comment by davidji99** [comment]
> and if you leave the pipeline empty for too long (hours? days?) it gets deleted automatically

Yeah, Heroku has a sweeper that discards these pipelines iirc.
