### ISSUE TITLE
terraform refresh does not update heroku_app config_vars

### ISSUE THREAD

**Issue by JamesBelchamber** [terraform-providers/terraform-provider-heroku#27]
I would expect the heroku_app config_vars to be updated on a `terraform refresh`, however this does not happen. Currently there is no way to ensure the state is in sync with the current environment variables.

**Comment by JamesBelchamber** [comment]
`all_config_vars` updates, `config_vars` does not. Hmm, this makes sense logically, but it's not desirable.

**Comment by joestump** [comment]
@JamesBelchamber Terraform expects that whatever it manages it manages 100% The `all_config_vars` is a way to expose human-managed Heroku configuration variables without taking over management of them. We only actively manage the `config_vars` that are in the Terraform code.

That being said, if you edit a variable in the dashboard that is present in `config_vars`, it should [get updated on read](https://github.com/terraform-providers/terraform-provider-heroku/blob/master/heroku/resource_heroku_app.go#L375-L397).
