### ISSUE TITLE
heroku_addon_attachment resource saves add-on ID using add-on name

### ISSUE THREAD

**Issue by cloudartisan** [terraform-providers/terraform-provider-heroku#40]
### Terraform Version

0.11.2

### Affected Resource(s)

- `heroku_addon_attachment`

### Terraform Configuration Files
```hcl
resource "heroku_app" "default" {
  name = "test-app"
}

resource "heroku_addon" "sumologic" {
  app  = "${heroku_app.default.name}"
  plan = "sumologic:free"
}

resource "heroku_addon_attachment" "sumologic" {
  app_id  = "${heroku_app.default.id}"
  addon_id = "${heroku_addon.sumologic.id}"
}
```

### Debug Output

Try planning and applying the same add-on attachment multiple times. See below for an example of a second run. Note that the `addon_id` in the state file has `addon_name` as its value, which is incorrect and results in forcing a new resource on every plan.

```
Terraform will perform the following actions:

heroku_addon_attachment.sumologic (new resource required)
       id:       "5382910f-92d4-4952-bc39-a92de2f87a72" => <computed> (forces new resource)
       addon_id: "sumologic-cubic-53500" => "1c7aa1ef-a6fc-47a4-abbb-b23512fc15a7" (forces new resource)
       app_id:   "sfdc-cb-rt-stg-ore" => "sfdc-cb-rt-stg-ore"
       name:     "SUMOLOGIC" => <computed>

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Expected Behavior

A second plan should show no changes.

### Actual Behavior

After the first plan and apply, every subsequent plan believes the attachment ID has changed and, since that is not an attribute that can be modified, plans to destroy and create the same attachment every time.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

This is due to [this line](https://github.com/terraform-providers/terraform-provider-heroku/blob/a001bfa69d29df16830b610b86d0a430e2d6d488/heroku/resource_heroku_addon_attachment.go#L71).

Likely a copy-and-paste error introduced by copying the app ID/name line above, which can be used interchangeably for apps, but not for other resources.

**Comment by davidji99** [comment]
closing this issue as the #39 was merged.
