### ISSUE TITLE
New heroku_space is "dirty" after terraform create

### ISSUE THREAD

**Issue by sheax0r** [terraform-providers/terraform-provider-heroku#42]
### Terraform Version
v0.10.8

### Affected Resource(s)
- heroku_space

### Terraform Configuration Files
```hcl
resource "heroku_space" "foobar" {
  name = "foobar-test-space"
  organization = "REDACTED"
  region = "virginia"
}
```

### Debug Output
https://gist.github.com/sheax0r/9ae0667a50e0cf2dc0465022e02c32c9

### Expected Behavior

`terraform plan` immediately after `terraform apply` should have showed no changes to execute.

### Actual Behavior
`terraform plan` immediately after `terraform apply` showed that it would result in these changes:

```
  ~ heroku_space.foobar
      trusted_ip_ranges.#: "1" => "0"
      trusted_ip_ranges.0: "0.0.0.0/0" => ""
```

### Steps to Reproduce
1. Create HCL files as described above.
2. `terraform apply`
3. `terraform plan`

**Comment by joestump** [comment]
BTW, I did try doing this:

```
Default: [1]string{"0.0.0.0/0"}
```

And it didn't work. Stepping through the code I couldn't find many obvious places where `trusted_ip_ranges` would get unset. My only two thoughts are:

* It's not getting saved to state properly on create. (This can be easily checked in the state file after the initial apply.)
* When TF does a read on a subsequent plan it is unable to pull/re-read the `trusted_ip_ranges` from state or the API.

Code path:

*  `resourceHerokuSpaceCreate` calls [`resourceHerokuSpaceRead `](https://github.com/terraform-providers/terraform-provider-heroku/blob/master/heroku/resource_heroku_space.go#L114)
* `resourceHerokuSpaceRead ` calls [`SpaceStateRefreshFunc `](https://github.com/terraform-providers/terraform-provider-heroku/blob/master/heroku/resource_heroku_space.go#L120).
* [`SpaceStateRefreshFunc`](https://github.com/terraform-providers/terraform-provider-heroku/blob/master/heroku/resource_heroku_space.go#L207-L209) returns before setting the `TrustedIPRanges` when the space is set to `allocating`, but `resourceHerokuSpaceCreate` [waits](https://github.com/terraform-providers/terraform-provider-heroku/blob/master/heroku/resource_heroku_space.go#L79-L90) for that attribute to flip to `allocating` it seems.
