### ISSUE TITLE
heroku_app changes after provisioning don't matter

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-heroku#43]
`organization`, `personal` and `region` apply, but don't change anything after the app has been created

**Comment by joestump** [comment]
@matti can you provide some example HCL for this? Both `organization` and `region` are marked as `ForceNew: true` in the TF schema. This _should_ force TF to recreate the resource on the next plan/apply.

**Comment by matti** [comment]
sorry stopped using heroku
