### ISSUE TITLE
deploying the application on the resource

### ISSUE THREAD

**Issue by lapots** [terraform-providers/terraform-provider-heroku#45]
I've got a simple `terraform` file 

```
variable "heroku_api_key" {}

provider "heroku" {
    email = "sebastrident@gmail.com"
    api_key = "${var.heroku_api_key}"
}

resource "heroku_app" "judge_re" {
    name = "judge-re"
    region = "us"

    buildpacks = [
        "heroku/java"
    ]
}
```

When I run `terraform apply` it successfully creates the infrastructure - the applicaiton and required buildpack. My question is - can I deploy the application (sources with Procfile) too? Or I should use separate tools like Jenkins or Travis to do that?

**Comment by JamesBelchamber** [comment]
My approach has been to deploy the code separately (from a CI tool like Jenkins or Travis). There's not a great way of doing this from Terraform, partly because of limitations with the Heroku Platform API.

**Comment by lapots** [comment]
I see. Well I am also doing deploy via Travis now.

**Comment by joestump** [comment]
Heroku CI with Heroku Pipelines is also a solid option.

**Comment by davidji99** [comment]
With the implementation of `heroku_slug`, `heroku_app_release`, and `heroku_formation`, one should enough to use terraform to deploy an application's code. Closing this. Feel free if to open a new issue if additional functionality is needed.
