### ISSUE TITLE
Broken space-related acceptance tests

### ISSUE THREAD

**Issue by sheax0r** [terraform-providers/terraform-provider-heroku#49]
Two spaces-related acceptance tests are broken:
* TestAccHerokuApp_Space
* TestAccHerokuSpace_Basic

To reproduce:

```bash
export TF_ACC=true
export HEROKU_EMAIL=...
export HEROKU_API_KEY=...
export HEROKU_ORGANIZATION=...
export HEROKU_SPACES_ORGANIZATION=...
go build && go test -timeout 300m -v ./heroku -run TestAccHerokuApp_Space
go build && go test -timeout 300m -v ./heroku -run TestAccHerokuSpace_Basic
```

Results:

```
--- FAIL: TestAccHerokuSpace_Basic (432.55s)
	testing.go:434: Step 1 error: After applying this step, the plan was not empty:

		DIFF:

		UPDATE: heroku_space.foobar
		  trusted_ip_ranges.#: "0" => "2"
		  trusted_ip_ranges.0: "" => "8.8.8.8/32"
		  trusted_ip_ranges.1: "" => "8.8.8.0/24"

		STATE:

		heroku_space.foobar:
		  ID = 681d984f-755d-47ac-8d4f-c0750aabb2ef
		  name = tftest-wxqfor2xbj
		  organization = redacted
		  region = virginia
		  trusted_ip_ranges.# = 0
```

and
```
--- FAIL: TestAccHerokuApp_Space (383.01s)
	testing.go:434: Step 0 error: After applying this step, the plan was not empty:

		DIFF:

		UPDATE: heroku_space.foobar
		  trusted_ip_ranges.#: "1" => "0"
		  trusted_ip_ranges.0: "0.0.0.0/0" => ""

		STATE:

		heroku_app.foobar:
		  ID = tftest-ay1rp1qbdy
		  acm = false
		  all_config_vars.% = 1
		  all_config_vars.FOO = bar
		  config_vars.# = 1
		  config_vars.0.% = 1
		  config_vars.0.FOO = bar
		  git_url = https://git.heroku.com/tftest-ay1rp1qbdy.git
		  heroku_hostname = tftest-ay1rp1qbdy.herokuapp.com
		  name = tftest-ay1rp1qbdy
		  organization.# = 1
		  organization.0.locked = false
		  organization.0.name = redacted
		  organization.0.personal = false
		  region = virginia
		  space = tftest-gpiudrvi2z
		  stack = heroku-16
		  web_url = http://tftest-ay1rp1qbdy.herokuapp.com/

		  Dependencies:
		    heroku_space.foobar
		heroku_space.foobar:
		  ID = 82f6f2d7-cb70-49f4-8bf2-aa69f78bc27e
		  name = tftest-gpiudrvi2z
		  organization = redacted
		  region = virginia
		  trusted_ip_ranges.# = 1
		  trusted_ip_ranges.0 = 0.0.0.0/0
```

This might be related to #42

**Comment by sheax0r** [comment]
@bernerdschaefer @Xe I believe this may be related to the problems with getting the acceptance tests to pass:

https://github.com/sheax0r/terraform-provider-heroku/blob/321621bad7964fce23b39cc56aa6492a77e4c6bf/heroku/resource_heroku_space.go#L92

I think `GetOk` only returns `true` if the value from the `ResourceData` object is a *non-zero* value. I believe furthermore that the empty array is being treated as a zero value. Therefore, if the user doesn't set a value (or sets it to `[]`), this code ends up doing nothing - which actually leaves the space using the *default value from heroku* for trusted ip ranges - and the default value is `[0.0.0.0]`. Thus, after a creation, spaces that don't specify a value end up not in sync - they've recorded an empty array, but heroku has created a space with an array containing "0.0.0.0".

Now I need to think about how we fix this. I'm coming at this still fairly new to go and it's getting late in the day. I think we might need to just not use `GetOk` here, but use some other way of getting the value out instead.

BTW [here is the bit where GetOk checks for zero values](https://github.com/sheax0r/terraform-provider-heroku/blob/321621bad7964fce23b39cc56aa6492a77e4c6bf/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go#L98), I think this is making our use of GetOk problematic.

Does this make sense?  I don't yet understand the failure of `TestAccHerokuSpace_Basic` - but one problem at a time.

**Comment by talbright** [comment]
These tests have been running ok for a while I believe, can we close this @davidji99?

**Comment by davidji99** [comment]
Yeah @talbright, closing this.
