### ISSUE TITLE
heroku_domain does not gracefully handle missing resources

### ISSUE THREAD

**Issue by robertrossmann** [terraform-providers/terraform-provider-heroku#50]
It seems that the `heroku_domain` does not gracefully handle situations where the previously-created domain has been deleted outside of Terraform. I think I also saw the same issue when trying to add a custom domain to an app via Terraform for the first time, but the domain name already exists on the app.

I am not certain about the intended behaviour within Terraform ecosystem about the latter (trying to create something that already exists), but the former definitely seems like a bug to me (trying to read the state of a resource which no longer exists or trying to delete a resource which no longer exists).

Looking at the source code, the error seems to come from here:

https://github.com/terraform-providers/terraform-provider-heroku/blob/aa9862241aa9aa3e5fed08bc1a9166b3f54bd6c1/heroku/resource_heroku_domain.go#L98-L101

And I see similar error handling pattern when trying to delete the domain:

https://github.com/terraform-providers/terraform-provider-heroku/blob/aa9862241aa9aa3e5fed08bc1a9166b3f54bd6c1/heroku/resource_heroku_domain.go#L87-L89

And, as a side note - while not actually observing this behaviour, this error handling pattern is also present in the `heroku_pipeline`, which would indicate a similar problem as described above:

https://github.com/terraform-providers/terraform-provider-heroku/blob/aa9862241aa9aa3e5fed08bc1a9166b3f54bd6c1/heroku/resource_heroku_pipeline.go#L102-L104

### Terraform Version

Terraform v0.11.3
+ provider.heroku v0.1.2

### Affected Resource(s)

- heroku_domain

### Terraform Configuration Files
```hcl
resource "heroku_app" "api" {
  name   = "example-api-development"
  region = "eu"

  buildpacks = [
    "heroku/nodejs",
  ]

  organization {
    name = "example"
  }
}

resource "heroku_domain" "api" {
  app      = "${heroku_app.api.name}"
  hostname = "api-development.example.com"
}
```

### Expected Behavior

The domain should have been recognised as missing and marked for creation.

### Actual Behavior

`terraform plan` panicked because the resource which was previously created by terraform (and was thus in the state) no longer exists.

### Steps to Reproduce

1. Using Terraform, create a Heroku app and attach a custom domain with the `heroku_domain` resource
1. Remove the custom domain from the app via Heroku dashboard
1. Run `terraform plan` again
1. Observe crash

### Important Factoids

None that I am aware of.

**Comment by bflad** [comment]
Hi @robertrossmann! 👋  Thank you very much for reporting this issue and sorry that you ran into trouble here.

Does it just return the error message or does Terraform actually panic (completely stop)? If its the latter, can you please provide the panic message from the debug logs? You can find where it starts  via a line starting with `panic: `.

For a few of the other Terraform providers (sorry I'm not directly familiar with Heroku so it may already be implemented in some other resources as well), we have a pattern like the following during deletion, which allows Terraform to not worry about resources that are already deleted:

```go
// call SDK deletion method
if err != nil {
  if /* logic to determine if it was an error for trying to delete a non-existent resource */ {
    return nil
  }
  return fmt.Errorf("...")
}
```

**Comment by bflad** [comment]
Oh! I should also note that during read functions, we can implement something similar as well:

```go
// call SDK read method
if err != nil {
  if /* logic to determine if it was an error for trying to read a non-existent resource */ {
    log.Printf("[WARN] ... %q not found, removing from state", d.Id())
    d.SetId("")
    return nil
  }
  return fmt.Errorf("...")
}
```

**Comment by robertrossmann** [comment]
Hi @bflad! Thanks for jumping in. Here is the full log report from running `terraform plan` right after I have deleted one of the Heroku domains previously created via `heroku_domain` resource.

```
> terraform plan

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.global: Refreshing state...
aws_s3_bucket.media: Refreshing state... (ID: example.com)
aws_sns_topic.alerts: Refreshing state... (ID: arn:aws:sns:eu-west-1:123:example-alerts)
heroku_app.api: Refreshing state... (ID: example)
data.template_file.log-group: Refreshing state...
aws_cloudwatch_log_group.api: Refreshing state... (ID: example/development)
aws_cloudwatch_metric_alarm.errors: Refreshing state... (ID: example-errors)
aws_cloudwatch_log_metric_filter.errors: Refreshing state... (ID: example-errors)
heroku_domain.api: Refreshing state... (ID: 95a1047c-c4d9-42c8-9fa2-1b127eed59cd)
heroku_pipeline_coupling.api: Refreshing state... (ID: a51d7afa-6509-4493-9868-dfd1688d8f1d)
heroku_app_feature.runtime-metadata: Refreshing state... (ID: example:33146ed7-199e-4a8a-b648-08fd0b52e10d)
heroku_addon.database: Refreshing state... (ID: 6b8a1e14-c416-4b97-bc7d-33ccb7ff208d)

Error: Error refreshing state: 1 error(s) occurred:

* heroku_domain.api: 1 error(s) occurred:

* heroku_domain.api: heroku_domain.api: Error retrieving domain: Get https://api.heroku.com/apps/example/domains/95a1047c-c4d9-42c8-9fa2-1b127eed59cd: Couldn't find that domain name.
```

No further output is generated and the command exits with exit code `1`.

It does not exactly say `panic: ...` but it sure stops from performing any further tasks. 🤔

**Comment by davidji99** [comment]
Hey @robertrossmann, 

It sounds like this is a situation where the resource, `heroku_domain` was managed by terraform but also managed outside of terraform aka manually. My understanding of terraform usage (someone correct me if there's another side to this statement) is once resource(s) are managed by terraform in code, one should try to only make resource changes via terraform. Making resources changes manually along with terraform defeats the version control benefit of managing infrastructure as code. In your case, I'd like to know why the `heroku_domain` was deleted in the first place and who deleted it. Plus, it means there isn't a single source of truth for resources that are managed by terraform.

Also, the error style you mentioned is actually pretty common from my experience. Take this line from the [AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_lb.go#L251). It errors out if a LB fails to be created. I personally prefer if it errors out if the heroku API complains it can't create the domain. Then I know I need to do import the existing domain into terraform first and then proceed accordingly.

I believe terraform also can save partial state so you don't need to start from 0 when you run `apply` again.

**Comment by robertrossmann** [comment]
Hello @davidji99,

I can understand that terraform should error out when not being able to create a resource (even if it failed to create it because that resource already exists) as that can have disastrous consequences.

However, failing to destroy a resource simply because the resource is already destroyed _or_ failing to create a resource which previously existed but does not exist anymore is also somewhat counter-intuitive with regard to what terraform is supposed to do (to my understanding) - bring the infrastructure to a prescribed state.

The reason why a resource no longer exists is, I believe, not relevant to this issue - it might have been deleted by accident, or it might have been deleted by someone who is not aware of the current infrastructure management strategy, or for many other reasons. We are but human beings. 😇

**Comment by davidji99** [comment]
Ah good point @joestump. Thanks for the explanation!
