### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by cyx** [terraform-providers/terraform-provider-heroku#70]
Greetings,

There's been awesome progress and development so far. I tried to search details around release cadence and such. Are there plans for when 0.2.0 will come out?

**Comment by davidji99** [comment]
Hey @cyx,

I'm going to fix up #62 and I believe you had a PR pending as well. Once we get those in, we can ask hashicorp to perform a release. I think we should just move to `1.0.0` (hashicorp would like us to do this). Thoughts?

**Comment by cyx** [comment]
That sounds good! I'll try to wrap up my PR tonight

**Comment by cyx** [comment]
@davidji99 Just wrapped up the PR. Please let me know if that looks good.

**Comment by davidji99** [comment]
Just fyi, asking hashicorp on getting a new release out now.

**Comment by cyx** [comment]
Nice!

**Comment by cyx** [comment]
Just saw that 1.0.0 has been released. Thanks for all the hard work everyone!
