### ISSUE TITLE
Addon attachments are always re-created

### ISSUE THREAD

**Issue by isaacseymour** [terraform-providers/terraform-provider-heroku#73]
### Terraform Version
0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- heroku_addon_attachment

### Terraform Configuration Files
```hcl
heroku_app "app1" {
  ...
}

heroku_addon "addon1" {
  app = "${heroku_app.app1.name}"
  ...
}

heroku_app "app2" {
  ...
}

heroku_addon_attachment "addon1-app2" {
  app_id = "${heroku_app.app2.id}"
  addon_id = "${heroku_addon.addon1.id}"
}
```

### Expected Behavior
Once applied, re-planning should require no changes

### Actual Behavior
Plan includes:
```
-/+ heroku_addon_attachment.addon1-app2 (new resource required)
      id:       "[UUID 1 removed]" => <computed> (forces new resource)
      addon_id: "[UUID 2 removed]" => "[addon1 name removed]" (forces new resource)
      app_id:   "app2" => "app2"
      name:     "MY_NAME" => "MY_NAME"
```

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

### Important Factoids
I think this is because the `id` attribute of the `heroku_addon` is its name, not its UUID. Therefore, when interpolating the HCL, terraform thinks the `heroku_addon_attachment` should be between `app2` and `addon1.name`, but in the state it's between `app2` and `addon1's UUID which is not in the state at all`. Therefore, every plan requires re-creating the addon attachment.

### References
I think this was introduced by #39 .

**Comment by davidji99** [comment]
This is interesting. I added a fix in #64 because the original version gave us the same problem you are experiencing @isaacseymour - a dirty re-plan.

The battle of id vs name..

**Comment by isaacseymour** [comment]
So the issue is that the `heroku_addon` does not expose its uuid as an attribute - both `.id` and `.name` return something like `postgresql-word-1234`. It'd be fine if `.id` returned the uuid, and `.name` returned the name.

**Comment by davidji99** [comment]
ah gotcha @isaacseymour, i'll take a look at this.

**Comment by isaacseymour** [comment]
Hey @davidji99, did you get a chance to look into this?

**Comment by davidji99** [comment]
I'll take a look this week.

**Comment by davidji99** [comment]
hey @isaacseymour,

When you look at your state file for a heroku addon, what is the value of the `id`? For example, for us it would be

```
"heroku_addon.kafka": {
"type": "heroku_addon",
"depends_on": [
"heroku_app.kafka.*"
],
"primary": {
"id": "<SOME_UUID>",
"attributes": {
},
"meta": {},
"tainted": false
},
"deposed": [],
"provider": "provider.heroku"
```

And the id of the `addon` is set to the `id` here https://github.com/terraform-providers/terraform-provider-heroku/blob/master/heroku/resource_heroku_addon.go#L105. Maybe I'm missing something else here?

**Comment by isaacseymour** [comment]
ok so for the addon we get something like:
```json
"type": "heroku_addon",
"depends_on": [],
"primary": {
"id": "postgresql-<word>-<number>",
"attributes": {
"app": "<appname>",
"config_vars.#": "1",
"config_vars.0": "HEROKU_POSTGRESQL_<COLOUR>_URL",
"id": "postgresql-<word>-<number>",
"name": "postgresql-<word>-<number>",
"plan": "heroku-postgresql:standard-0",
"provider_id": "resource<number>@heroku.com"
},
"meta": {},
"tainted": false
},
"deposed": [],
"provider": "provider.heroku"
```

and the attachment looks like:
```json
"type": "heroku_addon_attachment",
"depends_on": [
"heroku_addon.<terraform name>",
"local.common"
],
"primary": {
"id": "<uuid>",
"attributes": {
"addon_id": "postgresql-<word>-<id>",
"app_id": "<app name>",
"id": "<uuid>",
"name": "<name>"
},
"meta": {},
"tainted": false
},
"deposed": [],
"provider": "provider.heroku"
```

**Comment by davidji99** [comment]
I'm not sure how you got the addon `name` as the `id` in the state file since `resource_heroku_addon.go` L173 sets the `id` as the addon id. If the provider set the name like in `resource_heroku_app` L331 (for example), I could see how the change I added would cause issues.

When a few internal teams used the provider v0.1.2, we would always get the same dirty plan (#40) since `addon_id = "${heroku_addon.addon1.id}"` in the `.tf` file returns the UUID, not the NAME. 

Have you guys always used the public version of the provider?

An alternative solution that I'm looking at is add a migration file to  change NAME -> UUID.

**Comment by isaacseymour** [comment]
Yeah, we just use the public version as far as I know, and default to
whatever the latest release is (although now pinned to the last <1.0
release).

**Comment by davidji99** [comment]
Interesting, thanks for the info. I can't see how the `addon` id could have been the `NAME` instead of the `UUID` when storing that resource in state.

I've changed the scope of #84 to add a migration for both `heroku_addon` & `heroku_addon_attachment` to use the `addon`'s UUID instead of name. I don't have a state file that's using `NAME` so I am wondering if you know how to build the provider and use it locally in order to see if `terraform plan` is clean?

**Comment by isaacseymour** [comment]
Sorry for slow response, been on holiday. We actually never run terraform locally - it's only configured in CI, and I'm not sure how to go about building the version from master...

**Comment by davidji99** [comment]
@isaacseymour All good. Could you try a `terraform init && terraform plan` of the current provider version?

**Comment by isaacseymour** [comment]
Sorry, finallllly got round to trying this out...looks like #84 did the trick. Thanks!

**Comment by thomasleese** [comment]
I'm experiencing this same problem and I can't work out how to run the migrations in #84 to fix it... (I'm not too familiar with how Terraform works internally).

My state file looks like this (found by running `terraform show`):

```
resource "heroku_addon" "staging-database" {
    app         = "..."
    config_vars = [
        "DATABASE_URL",
    ]
    id          = "postgresql-contoured-..."
    name        = "postgresql-contoured-..."
    plan        = "heroku-postgresql:hobby-dev"
    provider_id = "..."
}
```

If it helps, I imported this addon into my state file using `terraform import ...`. I know there was a question about how it happened that the `id` was the same as the `name` and perhaps there is a bug there. I tried to look through the code to figure out if this was the case but I'm not familiar enough with Go or Terraform.

My guess at the moment is that the state file was already in version 2 before I ran the `terraform import` command so the migration in #84 isn't being run. I could manually edit the data in my state file (I'm using a Postgres remote backend) but I'm a bit worried about doing so if it breaks something else.

**Comment by thomasleese** [comment]
So I think I figured out how this happened. I had use `terraform import` with the name of the database addon as the argument, which worked, but set the id of the database to the name.

I just tried again an import but using the ID of the database, and it worked like before, but this time the state is correct.

**Comment by davetron5000** [comment]
I am also having this problem.  I created the attachment using Terraform and right after that a plan said it would replace it.  I went ahead and let it, and it still says it will replace it.

I removed it from state and re-imported it (which required using the databases ID and not the addon's ID).

It wants to change the add_on_id to the addon's name e.g. `«some uuid» -> postgresql-«name»-«number»`

I'm on the latest released version of the provider and the latest version of Terraform:

```
> terraform -version
Terraform v0.12.24
+ provider.heroku v2.4.0
```

**Comment by mars** [comment]
Thanks for the notification @davetron5000.

@davidji99  this was the kind of "noncovergent apply" problem I mentioned regarding changing Terraform state IDs from `name` to `id`.

Even though the API accepts either `name` or `id` as an identifier, it always returns `name`. So, Terraform has to deal in `name` as the `id`.

**Comment by davidji99** [comment]
> Even though the API accepts either `name` or `id` as an identifier, it always returns `name`. So, Terraform has to deal in `name` as the `id`.

Most resources' API return the UUID as well no?

**Comment by davetron5000** [comment]
> Anyhow, please open a new issue @davetron5000 with the necessary info and we can take a look at it. Thanks!

#264
