### ISSUE TITLE
shield attribute not imported for spaces

### ISSUE THREAD

**Issue by watsonian** [terraform-providers/terraform-provider-heroku#75]
### Terraform Version
```
Terraform v0.11.7
+ provider.external v1.0.0
+ provider.google v1.14.0
+ provider.heroku v1.0.0
+ provider.null v1.0.0
```

### Affected Resource(s)
- heroku_space

### Terraform Configuration Files
```hcl
variable space_name {}

resource "heroku_space" "default" {
  name              = "${var.space_name}"
  organization      = "my-org"
  region            = "virginia"
  trusted_ip_ranges = ["0.0.0.0/0"]
}
```

### Debug Output
```
-/+ heroku_space.default (new resource required)
      id:                          "my-space-uuid" => <computed> (forces new resource)
      name:                        "my-space" => "my-space"
      organization:                "my-org" => "my-org"
      outbound_ips.#:              "4" => <computed>
      region:                      "virginia" => "virginia"
      shield:                      "" => "false" (forces new resource)
      trusted_ip_ranges.#:         "1" => "1"
      trusted_ip_ranges.217649824: "0.0.0.0/0" => "0.0.0.0/0"
```

### Actual Behavior
After importing an existing space successfully with `terraform import heroku_space.default $UUID` and then running `terraform plan`, it immediately wanted to destroy and recreate the space due to the `shield` attribute needing to be set. It looks like https://github.com/terraform-providers/terraform-provider-heroku/pull/63 added this attribute, but didn't update `resourceHerokuSpaceRead` to pull in the new `shield` value on import.

### Steps to Reproduce
1. Create a fresh non-shield Heroku space
2. Import that space with `terraform import heroku_space.default $UUID`
3. Run `terraform plan`

**Comment by bernerdschaefer** [comment]
We're actually seeing this for all space resources created before #63, not just imported ones. It requires some manual state fiddling to get the plans correct.
