### ISSUE TITLE
heroku_formation does not support Free or Hobby dyno types

### ISSUE THREAD

**Issue by dtaylor-sfdc** [terraform-providers/terraform-provider-heroku#78]
### Terraform Version

0.11.2

### Affected Resource(s)

- `heroku_formation`

### Terraform Configuration Files
```hcl
resource "heroku_formation" "formation" {
  app      = "myfreeapp"
  type     = "web"
  quantity = "1"
  size     = "Free"
}
```

### Panic Output

https://gist.github.com/dtaylor-sfdc/097fc83f1959cf4d86cff70ec7c29119

### Expected Behavior

Create a `heroku_formation` resource with a free dyno.

### Actual Behavior

Crash due to unexpected EOF.

### References

See:

https://devcenter.heroku.com/articles/dyno-types
https://devcenter.heroku.com/articles/heroku-enterprise#available-dyno-types

for all supported dyno types. Notice that the non-enterprise accounts include "Free" and "Hobby".

**Comment by talbright** [comment]
Hey there @dtaylor-sfdc 👋 😄

**Comment by dtaylor-sfdc** [comment]
Hi @talbright!!!
