### ISSUE TITLE
heroku_app.vault net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by holyketzer** [terraform-providers/terraform-provider-heroku#87]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.11.7
+ provider.heroku v1.0.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- heroku_app

### Terraform Configuration Files
```hcl
# Configure the Heroku provider
provider "heroku" {
  email   = "${var.heroku_email}"
  api_key = "${var.heroku_api_key}"
}

resource "heroku_app" "vault" {
  name   = "vault-${var.hub_branch}"
  region = "${var.heroku_region}"

  config_vars {

  }

  buildpacks = [
    "https://github.com/deeplearninc/heroku-buildpack-vault"
  ]
}
```

### Debug Output
https://gist.github.com/holyketzer/84285cb263b48dd41085a7e6875101ae

### Expected Behavior
It should create heroku app

### Actual Behavior
it fails with TLS handshake timeout error

### Steps to Reproduce
`terraform apply`

**Comment by talbright** [comment]
I don't think this is an issue with the provider. If you look at https://gist.github.com/holyketzer/84285cb263b48dd41085a7e6875101ae#file-heroku-terraform-L137 you'll see there are connectivity issues with other endpoints.

**Comment by talbright** [comment]
@davidji99 I think we can close this one.
