### ISSUE TITLE
Support Pipeline Ownership

### ISSUE THREAD

**Issue by chdsbd** [terraform-providers/terraform-provider-heroku#94]
### Terraform Version
```
❯ terraform -v
Terraform v0.11.7
+ provider.heroku v1.1.0
```

### Affected Resource(s)
- heroku_pipeline

### Terraform Configuration Files
```hcl
resource "heroku_app" "production" {
  name = "test-app-production"
}
```

### Expected Behavior
`heroku_pipeline` should have a key to assign ownership of a pipeline. Pipelines without an owner are deprecated according to the heroku docs and show an warning banner: https://devcenter.heroku.com/articles/pipeline-ownership-transition

### Actual Behavior
pipelines are created without an owner.

### Steps to Reproduce
1. `terraform apply`

**Comment by davidji99** [comment]
This might be a limitation on the Heroku Platform API itself as https://devcenter.heroku.com/articles/platform-api-reference#pipeline doesn't have an option to specify the owner. Without API support, it might not be possible to do this via terraform.

**Comment by chdsbd** [comment]
That's a shame. This issue should probably be tagged `Heroku API Support`.

**Comment by talbright** [comment]
The ability to assign an owner exists now, but that version of the API is not marked stable. Once it is we can easily add this.

**Comment by slykar** [comment]
@talbright It has been some time since the introduction of the new API in Heroku CLI. Do you have any insight on when will it be more than a `prototype`?

The lack of this new functionality makes the Heroku provider quite useless for me right now. Maybe we could have "beta" version of the terraform Heroku provider too?

**Comment by slykar** [comment]
Thanks for the answer. I would love to get some follow up on this. 

Of course, my previous answer was a bit exaggerated, but there is some frustration that comes with needing to do some things manually or not knowing if there are some other "hidden" properties that require manual action.

I understand the point about stability of the provider. I was thinking if maybe there is a community fork of the provider that has an explicit experimental stability and includes the newest, non-documented features.

In the meantime I'll try to work around this problem using `local-exec` provisioners with cli.

**Comment by talbright** [comment]
The answer I have from the team is that it is on the roadmap, but I don't have an exact ETA. I would suggest proceeding with using `local-exec` as a workaround, as you mentioned.

**Comment by davidji99** [comment]
> I understand the point about stability of the provider. I was thinking if maybe there is a community fork of the provider that has an explicit experimental stability and includes the newest, non-documented features.

One can always fork and build the provider locally and/or on a CI tool (it's what my team does since we added some changes that might be too opinionated for the public provider). But for a forked heroku provider binary to be distributed by Hashicorp is another story and something that might need some insight from them.

**Comment by ninjaengineers** [comment]
Do you guys have an update for this?

> The answer I have from the team is that it is on the roadmap, but I don't have an exact ETA. I would suggest proceeding with using `local-exec` as a workaround, as you mentioned.

**Comment by dcherman** [comment]
Hey @talbright, is support for pipeline ownership still pending / in prototype?  It's not clear from https://devcenter.heroku.com/articles/platform-api-reference#pipeline-create whether or not it's still in prototype or not.  The example usage of that API includes an owner, but it's not explicitly listed as one of the supported params.

**Comment by davidji99** [comment]
I recently updated the `heroku-go` API client and `PipelineCreateOpts` still only has the name field as a parameter:
```
type PipelineCreateOpts struct {
	Name string `json:"name" url:"name,key"` // name of pipeline
}
```

The client is auto-generated from the Platform API schema so setting ownership is still not available when creating a pipeline.

@ninjaengineers & @dcherman, I suggest you submit support cases to Heroku indicating your desire for this enhancement. At the same time, Heroku support might be able to provide you with more information regarding the enhancement's status.

**Comment by mars** [comment]
@davidji99 it looks like you may be viewing an old version, because `PipelineCreateOpts` has an `Owner` field now 🎉 
https://github.com/heroku/heroku-go/blob/v5.2.0/v5/heroku.go#L2978

**Comment by davidji99** [comment]
Oh! I thought I was looking at latest `master`. Cool, this should be simple enough to add into the provider.
