### ISSUE TITLE
Support for ~/.netrc authentication

### ISSUE THREAD

**Issue by chdsbd** [terraform-providers/terraform-provider-heroku#95]
I think it would be a nice addition to support `.netrc` authentication.

Here is a Heroku go client issue that concluded clients should handle netrc: https://github.com/bgentry/heroku-go/issues/4

There is a client library already included to handle netrc but it doesn't seem to be used in this provider: https://github.com/terraform-providers/terraform-provider-heroku/tree/7948ef837c3f00f0fe672fd64bb679e67cdd09e8/vendor/github.com/bgentry/go-netrc

Heroku docs on netrc: https://devcenter.heroku.com/articles/authentication#netrc-file-format

**Comment by chdsbd** [comment]
I'll implement this if a contributor would accept the PR.

**Comment by davidji99** [comment]
Please go ahead and open a PR for this.

**Comment by davidji99** [comment]
Actually, I'll go ahead a take a stab at this.

**Comment by andreas-venturini** [comment]
Is it (in principal) possible for the provider plugin to also support gpg encrypted netrc files? (see https://devcenter.heroku.com/articles/authentication#gpg-encrypting-netrc-file)

**Comment by mars** [comment]
@andreas-venturini in principle yes it's possible, but encrypting `~/.netrc` wouldn't increase security because the private key to decrypt it would have to be present/available in the Heroku runtime.
